name: mecidiyehan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


    
  flutter_bluetooth_serial: ^0.4.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.1
  flutter_web_browser: ^0.17.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
 android: true
 ios: true
 image_path: "Asset/Mecidiye-Han-Logo.png"

flutter:
  uses-material-design: true
  assets:
    - Asset/
